name: Demonstrative workflow for uvus user CHR8486
on: 
    workflow_dispatch:
    issues:
        types: [opened, edited, transferred, reopened]

jobs:
  misc:
    runs-on: ubuntu-latest
    steps:
      - name: Printing the name of the trigger
        run: |
          echo "The trigger is ${{ github.event_name }}, and said action was triggered by ${{ github.actor }}."